### ISSUE TITLE
Does not display any article

### ISSUE THREAD

**Issue by pyluyten** [fbarthelery/geekttrss#11]
App was working properly for a long time. Recently, maybe 2 weeks ago, it started to show "No article" while there are.

The left panel show feeds, and show there are arctually articles, but either classic view or one single feed view logs then show "No Article".

Android One
Version 1.4.0-google

**Comment by pyluyten** [comment]
I recently upgraded to latest git master. Web interface shows "Tiny Tiny RSS v19.8 (ae5e08f)", a commit from August 16th. Probably issue started here but sorry i do not remember completely. 

What is certain is after git pull I had to login with admin account, probably to update db.

back to geekttrss : i cleared cache, even tried clearing storage, uninstalled app but the issue remains.

**Comment by fbarthelery** [comment]
Yes, that's what I suspected. There are some synchronization issue with latest server version. I'll release a fix in beta soon.

**Comment by fbarthelery** [comment]
I just release 1.4.1 to [beta channel](https://play.google.com/apps/testing/com.geekorum.ttrss). That should fix the issue (it should start rolling soon)
Let me know if it works for you

**Comment by pyluyten** [comment]
Great, beta fixes this! thanks!

_using the url to subscribe beta channel did not seem to do anything. Maybe it was jsut a matter of time. So i directly went to google play geekttrss page where you may find the beta version and directly install it, which was immediately effective_
