### ISSUE TITLE
FR: button to republish an article

### ISSUE THREAD

**Issue by abliss** [fbarthelery/geekttrss#15]
I would like to be able to add articles to my republished feed, as I can through the TTRSS web UI.

**Comment by fbarthelery** [comment]
Can you tell me more about your use case?

It seems that TinyTinyRss allows a few things regarding to the publish feeds : 

  * Change an article status to published : this makes the article appears in the "Published articles" feed

  * shareToPublished  : which create a new article with the specified `url`, `title`, and `content` and makes it appears in the "Published articles" feed

**Comment by abliss** [comment]
I mainly want the first one.  (I'm kinda interested in the second one too, but have never used it.) Thanks!

**Comment by fbarthelery** [comment]
First one is done in 1.6.5.

Open a new issue for the shareToPublished option if wanted
