### ISSUE TITLE
Geekttrss should show feed titles (or at least icons) in article list

### ISSUE THREAD

**Issue by hobgoblinsmaster** [fbarthelery/geekttrss#17]
I have many feeds and use almost all time "All articles" or "Fresh articles" views. In this views, it is important to know from which feed the articles comes from as:

- Not all my feeds use the author field.
- A number of feeds are from new sites or planets and I don't know all the authors of those.
- A few authors writes article for multiple of my feeds.

To help know quickly from which feed articles are, I'd love that the feed name appears just above the author name or at least that feed icon be on the left of the title or on the left of the author.

**Comment by fbarthelery** [comment]
I think that's a good idea. I personally never look at the author. :shrug: 

It will be good to have:
 - the feed icon always
 - the feed name if we are in a list that displays articles from multiple feeds
 - the author name if we are in a list that displays articles from a single feed

**Comment by hobgoblinsmaster** [comment]
Yes, I think this can be a very good compromise for most usages.

**Comment by fbarthelery** [comment]
Fixed in 1.6.0
