### ISSUE TITLE
Adding an button to set all article as read

### ISSUE THREAD

**Issue by pascalorama** [fbarthelery/geekttrss#19]
First thanks for this great app.

Maybe, it's just me , but i couldn't find a way to set all articles as read in one go. I've a lots of article and it's cumbersome to swipe every articles as read.

I'd suggest to use the floating button as a ''set all as read'' instead of refresh feed. As a vertical swipe already refresh the feed...

thanks in advance

**Comment by Dtrieb** [comment]
What did you think about the idea if you long press on a feed in the Menu to get a option to:

- Set all feed as read
- Set all feed as unread

**Comment by fbarthelery** [comment]
I like this idea. It seems more suitable than the Floating Action button.

**Comment by fbarthelery** [comment]
Done in 1.6.5
