### ISSUE TITLE
Crash after entering logindetails and domain

### ISSUE THREAD

**Issue by 1989gironimo** [fbarthelery/geekttrss#2]
Wanted to try out an alternative to the ttrss-reader available in f-droid, so this came quite handy.
But it crashes right after I put in my details from my selfhosted (Yunohost) ttrss instance.

my system details:
- LineageOS 15.1 with Magisk 18.0
- newest available version from geekttrss from f-droid

What else do you need to debug this?

**Comment by fbarthelery** [comment]
Hi, 

I haven't found Geekttrss on F-droid yet, can you send me a link ?

Regarding your crash, I think it should be fixed by f78159dd7fc4811b4f36319ce40c62bb8f618d9d but I haven't released a new version yet. I still have a few things to verify before releasing an update.

**Comment by fbarthelery** [comment]
I just release version 1.1.0. This bug should be fixed in this version. Let me know if it's not the case
