### ISSUE TITLE
Redundant HTTP requests when using HTTP Authentication

### ISSUE THREAD

**Issue by SunilMohanAdapa** [fbarthelery/geekttrss#24]
When using HTTP Authentication feature, the app seems to first send a request without the 'Authentication:' HTTP header. Later when the server responds with HTTP 401 and WWW-Authenticate header, then the second request contains the 'Authentication:' HTTP header and this one succeeds. This approach has two problems:

- It is very wasteful for network resources. The user has already configured the client to perform HTTP authentication. There is no reason not to send the 'Authorization:' header in the first try. This results in every call to server being made twice. On first load this results in twice the number of HTTP requests than necessary to perform the job.
- Server are not required to respond with HTTP 401 with 'WWW-Authenticate' header. See https://datatracker.ietf.org/doc/html/rfc2616#section-14.8 . In case of FreedomBox, we plan to support HTTP Basic authentication and a single sign-on on the same URL and so HTTP 401 response is not possible.

Some of the other TTRSS apps send a single HTTP request instead of two. This issue assumes that geekttrss only supportsBasic authentication and challenge/response mechanisms are not supported.

**Comment by fbarthelery** [comment]
Thanks for reporting. 

At the moment Geekttrss follow a "reactive" authentication protocol, and thus will send basic authentication only after the server sends the Authorization header. However, as the user explicitly asked for Basic Http authentication it seems right to use a pre-emptive protocol and send the credentials immediately.

I will work on this change when possible.

**Comment by fbarthelery** [comment]
Fixed in 1.6.4, let me know if you still have some issues
