### ISSUE TITLE
[Feature Request] Compact view for the list of feed headlines 

### ISSUE THREAD

**Issue by Dtrieb** [fbarthelery/geekttrss#26]
A list with only the headline of a feed would be great.

**Comment by fbarthelery** [comment]
Can you clarify your request ?  In my understanding it seems like this is exactly what the "All articles" menu item shows.

**Comment by Dtrieb** [comment]
I mean so
![Screenshot_20230526-034830](https://github.com/fbarthelery/geekttrss/assets/3650284/4cd9ef10-5d7c-4003-be05-3263aa42a1a3)

Only the Headline, Date and Time.
And perhaps a small picture on the left side in icon size.

**Comment by fbarthelery** [comment]
I guess you want a more compact view then. This is similar to #14

**Comment by Dtrieb** [comment]
> I guess you want a more compact view then. This is similar to #14

Yes  👍

**Comment by Gitoffomalawn** [comment]
I second (or third) this request.

**Comment by fbarthelery** [comment]
[1.6.7](https://github.com/fbarthelery/geekttrss/releases/tag/1.6.7) release added an option for a compact list on small screens
