### ISSUE TITLE
Mark articles as read while scrolling

### ISSUE THREAD

**Issue by 1989gironimo** [fbarthelery/geekttrss#3]
I do like the clean look of the app, instead of the a littlebit oldfashioned style the original ttrss-reader uses, but there's some room for improvements. For instance the possiblity to mark articles as read if you scroll down the articles.

**Comment by fbarthelery** [comment]
Yes, that's something I wanted to do but I haven't found a good way to do it for now. 
There is also the special case of small articles that don't need scrolling that need to be handle correctly.

**Comment by fbarthelery** [comment]
Should be fixed in c35140eb3bfb1f02336abc407351f39763589856 
It is now on the [beta channel ](https://play.google.com/apps/testing/com.geekorum.ttrss)
