### ISSUE TITLE
[BUG] Undo button can't be pressed

### ISSUE THREAD

**Issue by Gitoffomalawn** [fbarthelery/geekttrss#30]
When swiping an article to "Read" (right or left swipe), a white banner with the "undo" option pops up on the bottom of the screen. However, this banner doesn't take into account the positioning of on-screen buttons, which makes pressing "undo" impossible. 

This is a problem if accidentally swiping an article to "Read", as the article just disappears from the view with no way to retrieve it. The only way to get it back is marking it "Unread" in the TTRSS backend.

**Comment by Gitoffomalawn** [comment]
Just to add: this issue also affects the "Open in browser" button when an article is open (green, bottom right of screen). However, that button is big enough that you can press the top half. 

Curiously, the "Refresh" button, which is the same color and is located at the same place in the screen when the article overview is open, but with a different icon, is properly located above the on-screen navigation buttons.

**Comment by fbarthelery** [comment]
Thank you for reporting and sorry for the late answer.

I fixed this recently. I'll try to make a new release soon

**Comment by fbarthelery** [comment]
Fixed in [1.6.6](https://github.com/fbarthelery/geekttrss/releases/tag/1.6.6)
