### ISSUE TITLE
[Feature Request] Change default view

### ISSUE THREAD

**Issue by Gitoffomalawn** [fbarthelery/geekttrss#31]
The default view is now set to Magazine. It would would be nice to be able to set it to something else, such as a specific feed, or All Articles.

**Comment by fbarthelery** [comment]
In [1.6.7](https://github.com/fbarthelery/geekttrss/releases/tag/1.6.7) release you can create shortcut to a specific feed or specific view. The option is available in "Manage feeds".
It is not a change of the default view but I believe it can be used to open the app where you want.
