### ISSUE TITLE
does this app support connect url with ports?

### ISSUE THREAD

**Issue by ShadowProgging** [fbarthelery/geekttrss#33]
geekttrss won't connect to:

http://tt-rss.fritz.box:8280/tt-rss/

the other ttrss app from f-droid does connect ...

**Comment by fbarthelery** [comment]
It should work but I have to admit I don't remember ever tested it. What error do you get ? 
Is http://tt-rss.fritz.box:8280/tt-rss/ ? I can't access it from a browser

**Comment by fbarthelery** [comment]
Now that I think about it it's an http url not https. Https is required on latest Android version that may be your issue
