### ISSUE TITLE
Login fails with a longer password

### ISSUE THREAD

**Issue by jgoguen** [fbarthelery/geekttrss#4]
I set up TT-RSS and used a random 64-character password. The web UI was fine with that, so is the official TT-RSS Android app. This, however, popped up a system notification from Android Accounts saying there's a login failure. On the server I see only a single request to `/api` which returns HTTP200, no errors or logs emitted, and the app only shows a blank screen. Restarting the app, it gives me the login dialog again but I can only enter a new password.

I changed the password on TT-RSS to a shorter password, but still containing all the same character classes, and now the app works fine. I don't believe this is a limitation of Android Accounts, I have other accounts stored there which use 64-character random passwords. Please update to allow long passwords.

**Comment by fbarthelery** [comment]
Thank you for reporting this issue.

There was a bug with the encryption and storage of long password file. It should now be fixed by ac6433013f4cc7d451dc0ad6bc0b4743cf139e57
The fix should be available in the [beta channel](https://play.google.com/apps/testing/com.geekorum.ttrss) in a few hours
