### ISSUE TITLE
Add option to open links in native application

### ISSUE THREAD

**Issue by abcminiuser** [fbarthelery/geekttrss#8]
Currently attempting to open a link (in my case, a YouTube video from a subscription feed) opens my currently set web browser on my device instead of the set YouTube app.

It would be great if an option to instead open links with the default handler for that application could be added.

**Comment by fbarthelery** [comment]
I've made the following modifications: 
   - if there is an application that is not a web browser who can handle the link, it will be used.
   - otherwise use the browser.

It's released on the beta track for now. You can join the beta [here](https://play.google.com/apps/testing/com.geekorum.ttrss)
