### ISSUE TITLE
Unable to see log

### ISSUE THREAD

**Issue by airbete** [fbarthelery/geekttrss#9]
First installation. I try to connect to my server and I get:
Error: Unknown error (see log)

How do I see the log? There is just one button (login), no menu.

**Comment by simonwiles** [comment]
I just get "Unknown error" -- no mention of the log.  How can I go about debugging this?

**Comment by fbarthelery** [comment]
I'm sorry, this message was misleading. There is no log file.
You can find more information using `adb logcat`. 
Please open a new issue with some relevant information, I'd be happy to help
